### ISSUE TITLE
some question about your paper

### ISSUE THREAD

**Issue by Will-Hor** [xinychen/transdim#19]
From paper "Low-Rank Autoregressive Tensor Completion for Spatiotemporal Traffic Data Imputation"
Could you tell me how you calculated to get this formula?
![image](https://user-images.githubusercontent.com/38680839/210139705-0844b7ca-53be-472d-9af4-23d19fc4650a.png)

Looking forward your reply

**Comment by xinychen** [comment]
Your question is about the relationship between F-norm and inner product, right?

**Comment by Will-Hor** [comment]
Thanks, your answer helped me a lot. Looking forward to seeing more content updates of book in the future
