### ISSUE TITLE
How to apply LATC algorithm to my own dataset

### ISSUE THREAD

**Issue by Will-Hor** [xinychen/transdim#20]
I am glad to ask you a question. My dataset is not complete so I want to use LATC for completion. This means I don't have a dense_tensor, so what should I do? My dataset is a matrix with dimension 21x4081, but I added a new dimension to it and converted it into a tensor with dimension 21x1x4081.
If I use sparse_tensor.copy() to instead dense_tensor, RMSE and MAPE was nan.
![image](https://user-images.githubusercontent.com/38680839/210238272-497607da-d523-4f64-8cf0-6b689e2ba406.png)
Looking forward to your reply

**Comment by xinychen** [comment]
You can try to mask a certain amount of observations as missing values.
