### ISSUE TITLE
关于应用到二维矩阵数据的问题

### ISSUE THREAD

**Issue by xzscode** [xinychen/transdim#26]
我发现这些算法模型都是应用到三维张量的数据上面，那如果我的数据集是二维数据呢，比如说我想用到PEMS-BAY，METR-LA上面，我尝试的一个方法是把二维张量增加一个维度（原来是（N，T），变成（1，N，T），但是又会报内存不够的错误

**Comment by xinychen** [comment]
如果是data matrix，可以尝试https://github.com/xinychen/transdim/blob/master/imputer/LAMC-TNN.ipynb。

**Comment by xzscode** [comment]
只有这个适合data matrix吗，还有我想问一下二维张量增加一个维度的方法是否可行，原来是（N，T），变成（1，N，T），内存溢出之后我把（1，N，T）的规模缩小的到跟示例的数据集M*N*T一样了，但是程序运行的很慢，跑了一天才出两个iter，我想知道是不是维度增加的方式不对（（1，N，T）的计算量会很大？），可以变成（batch_size,N,T)吗？

**Comment by xinychen** [comment]
也还有其他方法，不妨试试https://github.com/xinychen/tracebase/blob/main/models/NoTMF.ipynb，这种方法计算效率很高。

**Comment by xzscode** [comment]
好的，非常感谢您及时的回复！
